### PR TITLE
Redirect to the orders page after creating an order.

### PR DESCRIPTION
**Pull request by kprakobkit**
Dude, took me forever to figure out how to test this.

### CODE REVIEW

**Comment by achiu8** [comment]
Sweeeet. Going to merge but looks like we have some flaky tests again..

**Comment by achiu8** [comment]
Oh, meant to say I rebuilt. Do we currently prevent merging of build fails or is that just on us?

**Comment by kprakobkit** [comment]
I don't think we prevent merging of failed builds. Do you know why it failed? Looking through the the build history but can't find it...

**Comment by achiu8** [comment]
Sorry should have documented.. I don't remember exactly but I think it was
a timeout on getOrders?

**Pull request merged**
